#cloud-config
autoinstall:
  version: 1
  locale: en_US
  keyboard:
    layout: us
  ssh:
    install-server: true
    allow-pw: true
    disable_root: true
    ssh_quiet_keygen: true
    allow_public_ssh_keys: true
  packages:
    - qemu-guest-agent
    - sudo
    - git
    - ansible
  storage:
    layout:
      name: direct
    swap:
      size: 0
  user-data:
    package_upgrade: false
    timezone: Europe/Berlin
    users:
      - name: hamza
        groups: [adm, sudo]
        lock-passwd: false
        sudo: 'ALL=(ALL) NOPASSWD:ALL'
        shell: /bin/bash
        # password is created with mkpasswd --method=SHA-512 --rounds=4096
        passwd: '$6$rounds=4096$HJe90IeZmIjSiV1y$CKFjuDz5Yb3g4hN29tnD7fzXNJDjSRqGHfuCKegcuTXaUbhUdMViINBnVHMYCN6oZSzj.w91aTu0opj/oD3J5/'
        # - or -
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCvTewkc81OI44WLCPUPPyDIMfvb4DA6aM938E8e8E68vs40MlSMGq7+CKgE3al+iAQ4HcwEH+TnCJJJ8YxJx5pfj4bhElf4BeAIfPGS/aLvddSu0EIap7gOjr66qyQdfHTJAR677Agvgyoyy5m12Ut2vmYj4oS1NVBe1bQ8kJxVLLrWviriA+mfrVQ/za4UHGYJgNI+FboYEaJt/GSESFBkUR6Izkwhyq6AFGxeli3/4BL0YpyQmAtGkyxwEAplTZJwAX0664deSvX/FRiNWNXknIUSVeDhuPhMtFI9deAXRTqzSd7rgHobPEg3WRBPxNmL8bVbOOUB1kQK/os6KeHcPRbISAyNlgZJvq32arXnE1/ph/6BnmtafbUP+gKO2l0x8mw24tsPUXPzseFYIm6lFGibZtRMM9wQ1voAC0FXkk8qGtc08mbDgykD77Dwq6b+FpDIekg4IYAM3vKY/iITMzqknVuSaaj8bDNQWqnMAFo04DA/IxIwaRUh+/ywqZKVq/mw4sb368H2WtA90jtzH3ZtOAsJUSzteHzZpCglAetlIE6spZh0cazL/SFQG4A2bmugqg0/35GzFK3vMxmaj0+l8F0Iao2i9H5o4HDhnr8C7KnXU1M7a0+TLjtRgr1k+aKB5aDldOoq4ym+hdygHELYQCPaHtIzXAJK2/Lkw==
    write_files:
    - path: /etc/ansible/ansible.cfg
      content: |
        [defaults]
        host_key_checking = False  # Disable host key checking (adjust for your security needs)
