---
- name: Run Prometheus role
  hosts: all
  become: yes
  roles:
    - prometheus
      vars:
      prometheus_targets:
        node:
        - targets:
          - localhost:9100
          - node.demo.do.prometheus.io
          labels:
            env: home-lab
    - pushgateway
    - grafana